# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KCFace_oc_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KCFace_oc_demo
#pod 'KCFaceKit', '~> 1.0.0'
end
